"""create the clicks field

Revision ID: 15570cd1d122
Revises: c59dc27ab10a
Create Date: 2026-01-28 15:54:07.745413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15570cd1d122'
down_revision: Union[str, Sequence[str], None] = 'c59dc27ab10a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('clicks', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'clicks')
    # ### end Alembic commands ###
