"""create the expired field

Revision ID: 1f9293ed923f
Revises: 04a8595cabf7
Create Date: 2026-01-30 20:52:34.717278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f9293ed923f'
down_revision: Union[str, Sequence[str], None] = '04a8595cabf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('expired', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'expired')
    # ### end Alembic commands ###
